/* tslint:disable */
/* eslint-disable */
/**
 * Stocky Backend
 * Stocky Backend API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EconomicEvent
 */
export interface EconomicEvent {
  /**
   * 고유 ID
   * @type {number}
   * @memberof EconomicEvent
   */
  id: number;
  /**
   * 이벤트 시간
   * @type {string}
   * @memberof EconomicEvent
   */
  time: string;
  /**
   * 이벤트 이름
   * @type {string}
   * @memberof EconomicEvent
   */
  name: string;
  /**
   * 국가 코드
   * @type {string}
   * @memberof EconomicEvent
   */
  country: string;
  /**
   * 영향도
   * @type {string}
   * @memberof EconomicEvent
   */
  impact: EconomicEventImpact;
  /**
   * 실제 값
   * @type {number}
   * @memberof EconomicEvent
   */
  actual: number | null;
  /**
   * 예상 값
   * @type {number}
   * @memberof EconomicEvent
   */
  estimate: number | null;
  /**
   * 이전 값
   * @type {number}
   * @memberof EconomicEvent
   */
  previous: number | null;
  /**
   * 단위
   * @type {string}
   * @memberof EconomicEvent
   */
  unit: string | null;
  /**
   * 생성 시간
   * @type {string}
   * @memberof EconomicEvent
   */
  createdAt: string;
  /**
   * 수정 시간
   * @type {string}
   * @memberof EconomicEvent
   */
  updatedAt: string;
  /**
   * 삭제 시간
   * @type {string}
   * @memberof EconomicEvent
   */
  deletedAt: string | null;
}

export const EconomicEventImpact = {
  Low: "low",
  Medium: "medium",
  High: "high"
} as const;

export type EconomicEventImpact = (typeof EconomicEventImpact)[keyof typeof EconomicEventImpact];
