name: Notify Slack Message Action
on:
  workflow_call:
    inputs:
      title:
        description: "Message Title"
        required: true
        type: string
      message:
        description: "Message Content"
        required: true
        type: string
      webhook_url:
        description: "Slack Webhook URL"
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": ${{ inputs.title }},
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ inputs.message }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
